spring.datasource.url=jdbc:postgresql://localhost:5432/skylink_database
server.port=7511
spring.datasource.username=mhcybroot
spring.datasource.password=MhR@2025
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# App Config
app.timezone=Etc/GMT+5
app.device.timezone=Etc/GMT+5

app.company.name=Smart Academic Infrastructure
app.testing=false
app.restrict=true


app.demo=false
server.servlet.session.timeout=1d

# Mail Config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mahmudul.skylink@gmail.com
spring.mail.password=cmjb eqnz ttxz uupd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# File Upload Limit
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
vapid.public.key=BNcXIMHMRCe4ZP0wHr4K3mp0kD1QgnPtM_y_nJf7ui9DC4xDkIruhnw2OcJ3nT2eXBitwXvKXIvSLTDTuKyGv5k
vapid.private.key=yn2k-xgKXGqpMPDKsBoD8NjWD5pEuyBj27lQtnNRxI0
vapid.subject=mailto: <mahmudul.skylink@gmail.com>
